"""Freeze the BindingGYM inter-assay (cluster) 5-fold split to a versioned file.

WHY THIS EXISTS
---------------
`GroupKFold` takes no random seed, but it assigns groups to folds by a greedy
"largest group -> currently lightest fold" rule.  BindingGYM's 25 assays fall into 14
clusters whose sizes tie heavily (6,4,2,2,2,1x9), so the assignment is decided entirely
by tie-breaking -- and sklearn changed that in 1.6.  Measured on this data:

    sklearn 1.2.1  (H3-DDG README pin)     -> assignment A
    sklearn 1.3.2  (BindingGYM.yml pin)    -> assignment A   (identical)
    sklearn 1.7.2                          -> assignment B   (CD19<->CXCR4 swap folds 2/3,
                                                              SARS2-RBD<->HLA-A2 swap folds 3/4)

So the fold membership is computed ONCE here under a checked sklearn version, written to
`data_splits/inter_assay_folds.tsv`, committed, and read by everything downstream.
Never recompute the split at training time.

Reproduces BindingGYM `training/main.py:348`:
    split = list(GroupKFold(n_splits=5).split(clusters, groups=clusters))
"""
import argparse
import os
import pandas as pd
import sklearn
from sklearn.model_selection import GroupKFold

EXPECTED_SKLEARN = ("1.2.1", "1.3.2")   # verified to agree on this data
N_SPLITS = 5


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mapping', default='./data/input/BindingGYM.csv')
    ap.add_argument('--cluster_tsv', default='./data_splits/BindingGYM_cluster.tsv')
    ap.add_argument('--out', default='./data_splits/inter_assay_folds.tsv')
    ap.add_argument('--allow_any_sklearn', action='store_true')
    args = ap.parse_args()

    if sklearn.__version__ not in EXPECTED_SKLEARN and not args.allow_any_sklearn:
        raise SystemExit(
            f'refusing to run: sklearn {sklearn.__version__} is not one of the verified '
            f'versions {EXPECTED_SKLEARN}. GroupKFold tie-breaking differs across versions '
            f'and would silently change the split. Use the h3ddg-reproduce env.')

    mapping = pd.read_csv(args.mapping)
    cl = pd.read_csv(args.cluster_tsv, sep='\t', header=None, names=['cluster', 'DMS_id'])
    cluster_map = dict(cl.set_index('DMS_id')['cluster'])

    dms_ids = list(mapping['DMS_id'])
    clusters = [cluster_map[d] for d in dms_ids]
    split = list(GroupKFold(n_splits=N_SPLITS).split(clusters, groups=clusters))

    rows = []
    for fold, (_, test_idx) in enumerate(split):
        for j in test_idx:
            rows.append(dict(DMS_id=dms_ids[j], cluster=clusters[j], test_fold=fold))
    out = pd.DataFrame(rows).sort_values(['test_fold', 'DMS_id']).reset_index(drop=True)

    assert len(out) == len(mapping) == 25, f'expected 25 assays, got {len(out)}'
    assert out['DMS_id'].nunique() == 25, 'each assay must appear exactly once'

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w') as f:
        f.write(f'# BindingGYM inter-assay (cluster) {N_SPLITS}-fold split\n')
        f.write(f'# generated by make_inter_assay_folds.py with scikit-learn {sklearn.__version__}\n')
        f.write(f'# source: GroupKFold(n_splits={N_SPLITS}).split(clusters, groups=clusters), '
                f'per BindingGYM training/main.py:348\n')
        out.to_csv(f, sep='\t', index=False)
    print(f'wrote {args.out}  (sklearn {sklearn.__version__})')
    print(out.groupby('test_fold')['DMS_id'].apply(list).to_string())


if __name__ == '__main__':
    main()
